language: python
python:
    - "3.4"
install: "pip install -r requirements.txt"
script:
    - SECRET_KEY="whatever" ./manage.py test
script:
  - py.test coveralls/tests.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
after_success:
  - coveralls