language: python
python:
    - "3.4"
install: "pip install -r requirements.txt"
script:
    - SECRET_KEY="whatever" ./manage.py test
    pip install coveralls
    coverage run --source=mypkg setup.py test
    coveralls
    