# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-05 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_auto_20190605_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='price',
            field=models.DecimalField(decimal_places=0, default='50', max_digits=2),
        ),
    ]
