# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-06 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0006_auto_20190605_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default='1', max_digits=1),
        ),
    ]
