# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-10 18:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('features', '0010_feature_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votesf',
            old_name='featurepk',
            new_name='feature',
        ),
        migrations.AlterUniqueTogether(
            name='votesf',
            unique_together=set([('voterf', 'feature')]),
        ),
    ]
