# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-31 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_auto_20190529_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='upvotes',
            field=models.DecimalField(decimal_places=0, default='1', max_digits=10),
        ),
    ]
