# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-31 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0005_auto_20190531_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('T', 'To Do'), ('D', 'Doing'), ('F', 'Finished')], default='T', max_length=1),
        ),
    ]
