# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-31 15:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugs', '0006_auto_20190531_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('To Do', 'To Do'), ('Doing', 'Doing'), ('Finished', 'Finished')], default='T', max_length=1),
        ),
        migrations.AddField(
            model_name='comments',
            name='bugpk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugs.Bug'),
        ),
    ]
