# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-31 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0007_auto_20190531_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('To Do', 'To Do'), ('Doing', 'Doing'), ('Finished', 'Finished')], default='To Do', max_length=1),
        ),
    ]
