# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-03 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0009_auto_20190602_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='upvotes',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=10),
        ),
    ]
