# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-04 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0011_auto_20190604_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
