# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-04 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0012_auto_20190604_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='content',
        ),
    ]
